version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: santa_test

  rspec:
    image: gcr.io/secretsanta-web/secretsanta-web:testing
    volumes:
      - .:/secretsanta
    command: "./run-tests.sh"
    depends_on:
      - postgres
    environment:
      DB_HOST_URL: postgres
