FROM ruby:2.5.3

# Installation of dependencies
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y nodejs

# Do not generate documentation when installing gems and fix shebang lines
RUN echo "gem: --no-rdoc --no-ri --env-shebang" >> "$HOME/.gemrc"

# Add Gemfile, install gems and copy over our application code
ENV RAILS_ENV production
ENV APP_HOME /secretsanta
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN bundle install --without development test
ADD . $APP_HOME

ENV SECRET_KEY_BASE mykey
RUN RAILS_ENV=production bundle exec rake assets:precompile

# Remove some directories to trim down the size of the image
RUN rm -rf /var/lib/apt /var/lib/dpkg /var/lib/cache /var/lib/log

# Run our app
CMD rm -f tmp/pids/server.pid \
  && bundle exec rake db:create \
  && bundle exec rake db:migrate \
  && bundle exec foreman s --procfile Procfile-prod
