FROM ruby:2.5.3-alpine

# Installation of dependencies
RUN apk update && apk upgrade
RUN apk add --update alpine-sdk postgresql-dev nodejs libc6-compat

# Add Gemfile, install gems and copy over our application code
ENV APP_HOME /secretsanta
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install --jobs $(nproc) --without development test
ADD . $APP_HOME

ENV SECRET_KEY_BASE mykey
RUN RAILS_ENV=production bundle exec rake assets:precompile

# Remove some directories to trim down the size of the image
RUN rm -rf /var/lib/apt /var/lib/dpkg /var/lib/cache /var/lib/log

# Run our app
CMD bundle exec rake db:create \
  && bundle exec rake db:migrate \
  && bundle exec foreman s --procfile Procfile-prod
